### DISCUSSION TITLE
File names?

### DISCUSSION THREAD

**Discussion by asmaloney** [robinraju/release-downloader#454] [Q&A] [answered]
I'm having troubles with file names. I'm trying to download the source from [this release](https://github.com/sbcl/sbcl/releases/tag/sbcl-2.2.5).

So I have (hardcoded tag for now):

```
      - name: Get Release Info
        run: |
          echo "RELEASE_TAG=sbcl-2.2.5" >> $GITHUB_ENV
          echo "Using tag: ${{ env.RELEASE_TAG }}"
      - name: Get SBCL source code
        uses: robinraju/release-downloader@v1.3
        with:
          repository: 'sbcl/sbcl'
          tag: ${{ env.RELEASE_TAG }}
          zipBall: true
      - name: Decompress
        run: |
          unzip "${{ env.RELEASE_TAG }}.zip"
          cd sbcl-${{ env.RELEASE_TAG }}
```

However I don't know how to sort out the file name.

- If I look at the link on the release page, it's `sbcl-2.2.5.zip`: https://github.com/sbcl/sbcl/archive/refs/tags/sbcl-2.2.5.zip
- If I download the file through that like, it creates a file called `sbcl-sbcl-2.2.5.zip`
- When I run the action, it does this (which gives yet another name - `sbcl-SBCL 2.2.5.zip`):
  ```
  Fetching release sbcl-2.2.5 from repo sbcl/sbcl
  Downloading file: sbcl-SBCL 2.2.5.zip to: /home/runner/work/sbcl-build/sbcl-build
  Done: /home/runner/work/sbcl-build/sbcl-build/sbcl-SBCL 2.2.5.zip
  ```

How do I get the downloaded file name to unzip it?

Thanks!

**Comment by robinraju** [comment]
When downloading a `zipBall` or `tarBall`, the action currently names the file as follows
`{repo-name}-{release name}.zip`
The release you're trying to download has the name `SBCL 2.2.5`. Thus it downloads a file with the name `sbcl-SBCL 2.2.5.zip`

you can try something like this for now
```
  - name: Decompress
    run: |
      ls -lrth
      unzip "sbcl-SBCL 2.2.5.zip"
      ls -lrth
```

I think the prefix `repo-name` to the file name is unnecessary. I'll remove that part and also keep the file name equivalent to the tag name.
Once it is fixed, you may use it as  `unzip "${{ env.RELEASE_TAG }}.zip"`

**Reply by robinraju** [reply]
A fix for this is now merged to `main`
You can use it using the commit hash until the next release is available as follows

```yaml

      - name: Get Release Info
        run: |
          echo "RELEASE_TAG=sbcl-2.2.5" >> $GITHUB_ENV
          echo "Using tag: ${{ env.RELEASE_TAG }}"
      - name: Get SBCL source code
        uses: robinraju/release-downloader@0431bf60ebfbe10b077c9e7d61b448ef16e9efc6
        with:
          repository: 'sbcl/sbcl'
          tag: ${{ env.RELEASE_TAG }}
          zipBall: true
      - name: Decompress
        run: |
          ls -lrth
          unzip "${{ env.RELEASE_TAG }}.zip"
          ls -lrth
```

**Reply by asmaloney** [reply]
Thanks Robin.

I think this repo is an unusual case though. Most tags I've seen are of the form `v1.5.2` in which case the file name you generate won't contain the name of the project: `v1.5.2.zip`

Don't we want `{repo-name}-{release-tag}.zip`?

Then it would become `sbcl-sbcl-2.2.5.zip` which matches the file as if I downloaded it manually.

**Reply by robinraju** [reply]
`{repo-name}-{release-tag}.zip` sounds reasonable. a `release-tag` may not contain space between its name. It was not the case previously, I was using the `release name` instead.

**Reply by robinraju** [reply]
can you try this one (latest commit on main),

```yaml
     - name: Get SBCL source code
       uses: robinraju/release-downloader@768e5668c501e732416580dbb1f56794f4d1f590
```
It creates file with name: `{repo-name}-{release-tag}.zip`

**Reply by asmaloney** [reply]
Great stuff - thank you for your help!

**Comment by asmaloney** [comment, marked as answer]
(To mark something as an answer it seems it can't be a response?)

Here's my final result:
```yaml
      - name: Get Release Info
        run: |
          echo "RELEASE_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      - name: Get SBCL source code
        uses: robinraju/release-downloader@768e5668c501e732416580dbb1f56794f4d1f590
        with:
          repository: 'sbcl/sbcl'
          tag: ${{ env.RELEASE_TAG }}
          zipBall: true
      - name: Decompress
        run: |
          echo "Using tag: ${{ env.RELEASE_TAG }}"
          ls -lrth
          unzip sbcl-${{ env.RELEASE_TAG }}.zip -d sbcl-${{ env.RELEASE_TAG }}
          ls -lrth
```

Thank you for your help!
