### DISCUSSION TITLE
Error 403 using this at SSO Organization Level

### DISCUSSION THREAD

**Discussion by fiddlermikey** [robinraju/release-downloader#472] [Q&A]
I think I'm running into a permissions issue but hoping someone can help shed light on this 403 error I'm getting. I have an action that takes an Organization and Repository Name as inputs and should pull the latest release artifact from the repo. 

I have tried various combinations to try to narrow this down. 

* As a user, I can pull my own public and private repos
* Transferred script to non-enterprise/SSO org
* As a Org (non-enterprise/SSO) I can pull my public and private repos
* Transferred action/workflow to Org using SSO
* Added personal PAN with full access and copied the key to a secret at the SSO Org level
* As SSO Org I can pull my user's public repos
* As SSO Org I get 403 error when trying to pull a public repo owned by the SSO Org

I find tables helpful, so I made one:
|Script owner|Target Repo Owner|Repo Visibility|Result|
|---|---|---|---|
|User|User|Private|Ok|
|UserOrg|UserOrg|Private|Ok|
|UserEntOrg|User|Public|Ok|
|UserEntOrg|UserEntOrg|Public|403 Error|

Can anyone help me understand what needs to be updated? Is it the repo or action that is failing authorization? How do I track that down?

Update: I just tried downloading the artifact from the same repo where this action is run from, so not even from a different repo, and received the 403 error.

The workflow file is pretty basic:

```
on:
  workflow_dispatch:
    inputs:
      org:
        description: 'Project to sign'
        default: 'fiddlermikey'
        required: true
      repo:
        description: 'Project to sign'
        default: 'integ-testing'
        required: true

jobs:
    runs-on: windows-latest

    steps:
    - name: Download Release Asset
      uses: robinraju/release-downloader@v1.4
      with:
        repository: "${{ github.event.inputs.org }}/${{ github.event.inputs.repo }}"
        token: ${{ secrets.TEST_PRIVATEACCESS }} # Org-level secret defined using personal PAN
        latest: true
        fileName: "*.zip"

```

**Comment by fiddlermikey** [comment]
I found the github-api-key was the problem, at least for public repos. Our company uses an Enterprise Account and it seems to be a required parameter in my case. I still cannot download from private repos. Is this by design?

**Comment by robinraju** [comment]
@fiddlermikey I recently added support for GH Enterprise as part of this issue #463 
It was added after the release of `v1.4`. You should be able to use it by specifying the commit hash from the `main` branch as follows.
A new input needs to be specified for Enterprise server `github-api-url`

```yaml
- uses: robinraju/release-downloader@0ea540940ee276d96c1b1aaed5e1118aaabdcec2
  with:
    repository: "owner/repo"
    latest: true
    fileName: "foo.zip"
    token: "your token"
    github-api-url: "https://[enterprise-hostname]/api/v3"
```

Can you try this and let me know if it works for you?
