### DISCUSSION TITLE
Need to download multiple release artifacts from multiple repos

### DISCUSSION THREAD

**Discussion by jeba-schulz-epam** [robinraju/release-downloader#605] [Q&A]
Hello

I have a use case to download multiple release artifacts based on tag from multiple repos. I see through this action i can download from one repo. if i need to download from multiple repos. how can i do that?

Any help toward this are welcome..!

Thanks

**Comment by robinraju** [comment]
You may use this action more than once in your job as multiple steps

```

steps:
  - name: Download from repo 1
    uses: robinraju/release-downloader@v1.7
    with:
      repository: "owner/repo-1"
      latest: true
      fileName: "foo.zip"

  - name: Download from repo 2
    uses: robinraju/release-downloader@v1.7
    with:
     repository: "owner/repo-2"
     latest: true
     fileName: "bar.zip"

```

**Comment by jeba-schulz-epam** [comment]
Hi Robin thanks for the response...I know we can have it as multiple times but in my use case since we need a large number of artifacts the workflow becomes very large and not in a reusable manner. Can we have some workaround to dynamically run this actions for an array of variables?

let me know your suggestions on this..

Thanks

**Comment by robinraju** [comment]
Maybe you can try using the matrix strategy for running your job

https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs

- Set an array of values 
- Use this matrix value in the action step
 https://tomasvotruba.com/blog/2020/11/16/how-to-make-dynamic-matrix-in-github-actions/

```
jobs:
 download_files:
    strategy:
      matrix:
        files: [file1.zip, file2.zip]

steps:
  - name: Download from repos
    uses: robinraju/release-downloader@v1.7
    with:
      repository: "owner/repo-1"
      latest: true
      fileName: ${{ matrix.files }}
```

> I haven't tried this. but this is just an idea.
