### ISSUE TITLE
Getting 400 on all downloads

### ISSUE THREAD

**Issue by FalconerTC** [robinraju/release-downloader#333]
**Describe the bug**
As of this morning, all downloads using this action are giving a 400

eg
```
Fetching latest release for repo RentTheRunway/<repo>
Downloading file: <tool>-linux-amd64.tar.gz to: /runner/_work/<runner>
Error: Unexpected response: 400
```

Curious if anyone else just started seeing this? Maybe the API changed today?

**To Reproduce**
1. Execute a download against a private repo

**Expected behavior**
It should successfully download the artifact

**Action Environment (please complete the following information):**
 - OS: ubuntu (self-hosted)

**Additional context**
I'm running with the following

```
      - uses: robinraju/release-downloader@v1.2
        with:
          repository: "RentTheRunway/<repo>"
          latest: true
          fileName: "<file>-linux-amd64.tar.gz"
          token: ${{ secrets.ACCESS_TOKEN_GITHUB }}
```
