### ISSUE TITLE
Unexpected response: 403

### ISSUE THREAD

**Issue by noonchen** [robinraju/release-downloader#347]
**Describe the bug**
macos-11 only, Error: [getlatestRelease] Unexpected response: 403 when downloading source code from numpy/numpy.

**To Reproduce**
```
jobs:
  macos-cp39:
    runs-on: macos-11
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9
          architecture: x64

      - uses: robinraju/release-downloader@v1.2
        name: Download latest numpy source
        with: 
          repository: "numpy/numpy"
          latest: true
          zipBall: true
          out-file-path: "downloads"
```

No issue in linux-latest so far. 
Github action link: https://github.com/noonchen/STDF-Viewer/runs/4549369806?check_suite_focus=true

Any suggestions what happened? It works pretty fine before.

**Comment by robinraju** [comment]
Unfortunately, this action is not tested against macOS runner yet. 
I found an issue reported earlier related to macOS runner here: https://github.com/actions/virtual-environments/issues/602

It says GitHub rate limits API calls from macOS runner and returns 403. A quick look at the issue gives me the impression that you should provide a token. (it's meaningless for public repos).

Can you try creating a [personal access token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token) and add it to the secrets of your repo.

try the following
```
uses: robinraju/release-downloader@v1.2
        name: Download latest numpy source
        with: 
          repository: "numpy/numpy"
          latest: true
          zipBall: true
          token: "{{secrets.YOUR_TOKEN_NAME}}"
          out-file-path: "downloads"
```
I'm not 100 % sure about this, but at least give it a try and let's see how it goes.
