### ISSUE TITLE
Retry on failure

### ISSUE THREAD

**Issue by mudler** [robinraju/release-downloader#439]
Thanks for building this action! that was exactly what I needed for some of my projects :)

**Is your feature request related to a problem? Please describe.**
When running this action on macOS runners, I hit #347 quite a lot of times. Restarting the job a couple of times eventually makes it successfull

**Describe the solution you'd like**
A way for the action to retry on failure, for example, by specifying a max number of retry attempts and a delay time in between 

**Describe alternatives you've considered**
- I've tried with https://github.com/marketplace/actions/retry-action, but running this action with it brings always a constant 404
- A separate job running on Linux runners and pass over the artifacts between jobs

**Additional context**
At https://github.com/c3os-io/c3os/ I'm planning to use this action to run upgrade tests from latest releases - but currently this is almost not doable at all for the problem mentioned above

**Comment by robinraju** [comment]
@mudler This is caused by GitHub rate limiting API calls from macOS runner.
This action uses the GH API under the hood. 

Can you try providing the default GitHub token as follows

```
- uses: robinraju/release-downloader@v1.3
  with:
    latest: true
    fileName: "foo.zip"
    token: ${{ secrets.GITHUB_TOKEN }}
```
You don't need to generate a new token. This one is available on the actions runtime. See: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret

If this works for you on macOS runner, I'll make this default to this action.

**Comment by robinraju** [comment]
Update:
A possible fix is merged in #441 

@mudler can you try using the latest commit from main as follows

```
- uses: robinraju/release-downloader@36fe95787d3f42ee0e69626e12775d15c7c14d38
  with:
    latest: true
    fileName: "foo.zip"
```
