### ISSUE TITLE
GIthub API URL is hard coded and does not work on github enterprise server

### ISSUE THREAD

**Issue by butler54** [robinraju/release-downloader#463]
**Describe the bug**
As above.

**To Reproduce**
Run the action on enterprise server - it will continue to target github.com and 404 (or 401 ) depending on the path. Worst case scenario is it downloads packages from github.com that could be malicious.

**Expected behavior**
Read from github enviroment the correct API server.

**Screenshots**
NA

**Action Environment (please complete the following information):**
 - OS: self hosted which is close to ubuntu latest

**Additional context**

**Comment by robinraju** [comment]
@butler54 Thanks for noticing this. I'll add an option to read api-url from the workflow config

**Comment by robinraju** [comment]
A fix for this is now merged to `main`. You may use it by specifying the commit hash until the next release is available as follows

```yaml
- uses: robinraju/release-downloader@0ea540940ee276d96c1b1aaed5e1118aaabdcec2
  with:
    repository: "owner/repo"
    latest: true
    fileName: "foo.zip"
    github-api-url: "https://[hostname]/api/v3"
```
