### ISSUE TITLE
Fail loudly when asset doesn't exist

### ISSUE THREAD

**Issue by pbrisbin** [robinraju/release-downloader#535]
**Describe the bug**

Hi there, and thanks for the great Action. We're using it to install one of our internal tools by downloading the binary asset from the latest release. Sometimes the CI/CD for that tool fails such that the release exists, but the asset we're looking for doesn't.

In such a case, `release-downloader` succeeds, and we fail in more confusing ways later. I think `release-downloader` should fail if it can't find the requested asset -- which would be much clearer for us.

**To Reproduce**

1. Have a project with a Release but no asset named `x86_64-linux.tar.gz`
2. Run this action with,

   ```yaml
   with:
     repository: that/project
     latest: true
     fileName: x-x86_64-linux.tar.gz
     token: ***
     tarBall: false
     zipBall: false
     out-file-path: .
   ```

**Expected behavior**

A clear error, something like:

> Asset `x-x86_64-linux.tar.gz` does not exist on latest Release ({release name})

**Screenshots**

![](https://files.pbrisbin.com/screenshots/screenshot.3048203.png)

**Action Environment (please complete the following information):**
 - OS: `ubuntu-latest`

**Additional context**

**Comment by robinraju** [comment]
@pbrisbin Thanks for reporting this. I'll try to find some time this week/next to add this `error reporting` to this action.

**Comment by robinraju** [comment]
@pbrisbin a fix this is just merged. you may test it by using the action from the main branch as follows; I can create a new release if you confirm it works as expected.

```
- uses: robinraju/release-downloader@e1f6dbdca9410fa93687edc6957bc19b11dc3665
  with:
    latest: true
    fileName: "foo.zip"
```
