### ISSUE TITLE
Download prereleases?

### ISSUE THREAD

**Issue by beeb** [robinraju/release-downloader#597]
**Is your feature request related to a problem? Please describe.**
I am not sure how to allow download of the latest prerelease.

**Describe the solution you'd like**
I would like a flag that allows me to include prereleases in the list of releases to pull from.

**Describe alternatives you've considered**
None

**Comment by PerryWerneck** [comment]
An option to download from the latest draft or pre-release. Maybee the same engine of oprypin/find-latest-tag@v1

**Comment by robinraju** [comment]
Downloading pre-release/draft is not supported by this action at the moment. It's a nice to have feature. I need to find some time to implement it. Or a PR is always welcome.

**Comment by robinraju** [comment]
Latest pre-release can be downloaded as follows

```
- uses: robinraju/release-downloader@v1.9
  with:
    repository: "owner/repo"
    fileName: "foo.zip"
    latest: true
    preRelease: true
```
