### ISSUE TITLE
Failing to run latest when fileName is not `release.tar.gz`

### ISSUE THREAD

**Issue by i-am-the-slime** [robinraju/release-downloader#601]
**Describe the bug**
I have a monorepo and just added another workflow for a different app. I made sure to tag its releases as `ai-annotator-release.tar.gz`. 

**To Reproduce**
This are the two steps in question. The first one only runs when input is not `latest` and it works. The second one is copy pasted and does **not** work. In another action the same thing does work and the only difference I can see is that:
 
  - I have `fileName: "ai-annotator-release.tar.gz`

```
    steps:
      # THIS STEP WORKS
      - name: Download specific release
        if: "${{ github.event.inputs.version != 'latest' }}"
        uses: robinraju/release-downloader@v1.7
        with:
          repository: ${{ github.repository }}
          fileName: "ai-annotator-release.tar.gz"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.inputs.version }}

      - name: Download latest release
        # THIS STEP FAILS 
        if: "${{ github.event.inputs.version == 'latest' }}"
        uses: robinraju/release-downloader@v1.7
        with:
          repository: ${{ github.repository }}
          fileName: "ai-annotator-release.tar.gz"
          token: ${{ secrets.GITHUB_TOKEN }}
          latest: true
```

**Expected behavior**
It should 

**Screenshots**
<img width="443" alt="image" src="https://user-images.githubusercontent.com/1588055/218979274-aff26755-c3a2-44fe-a6d8-8f5ffbfd1213.png">

**Action Environment (please complete the following information):**
 - OS: ubuntu-latest

**Additional context**
I'm not sure this is actually a bug or if I'm doing something wrong.

**Comment by robinraju** [comment]
Are you still facing this error? Can you check if your release is not marked as a pre-release/draft.

**Comment by i-am-the-slime** [comment]
Yes, this is still a problem. The lastest version does not respect the file name as far as I can tell:

```
Found latest release version: ai-annotator-2023-04-26|14-40
Error: Asset with name release.tar.gz not found!
```

It downloads the globally latest version: 
```
      - name: Download latest release
        if: "${{ github.event.inputs.version == 'latest-website' }}"
        uses: robinraju/release-downloader@v1.7
        with:
          repository: ${{ github.repository }}
          fileName: "release.tar.gz"
          token: ${{ secrets.GITHUB_TOKEN }}
          latest: true
```
