### ISSUE TITLE
"extract" from zip archive does not preserve permissions on Linux

### ISSUE THREAD

**Issue by eugeneko** [robinraju/release-downloader#670]
"executable" permission is lost when zip is extracted.

1. Prepare release zip archive with binaries with "executable" permissions
2. Download it via this action, `extract: true`
3. See that "executable" permissions are lost.

I would expect permissions to be preserved.

![image](https://github.com/robinraju/release-downloader/assets/8576192/bbcaf159-9c10-42e8-8de1-110dc67fecff)
![image](https://github.com/robinraju/release-downloader/assets/8576192/079c386b-80eb-4931-b3ed-d5379a5cc4ed)

OS: ubuntu-20.04

**Comment by robinraju** [comment]
We have a new release that changes the underlying library for extracting zip files.

```
- uses: robinraju/release-downloader@v1.10
  with:
    fileName: "foo.zip"
    latest: true
    extract: true
```
Let me know if you still see this problem
