### ISSUE TITLE
Upgrading to latest release produces new error

### ISSUE THREAD

**Issue by fiddlermikey** [robinraju/release-downloader#739]
I am in the process of hardening the security in our organization for our actions. After forking the repository and creating a tag for the latest (v1.10), the following error is displayed

`Error: Client network socket disconnected before secure TLS connection was established`

I was using v1.4 tag earlier which does not display this issue

**To Reproduce** Steps to reproduce the behavior:
Create a workflow:
```
jobs:
  codesign-binary:
    runs-on: windows-latest
    steps:
      - name: Download Release Asset
        uses: robinraju/release-downloader@v1.10
        with:
          repository: "organization/repository"
          token: ${{ secrets.token }}
          latest: true
          fileName: "*.zip"
          github-api-url: "https://organization.com/api/v3"
```
Change the v1.10 to v1.4 and the error does not appear

**Expected behavior** Release asset is downloaded

- OS: [e.g. windows-latest]
