### ISSUE TITLE
No assets found in release.

### ISSUE THREAD

**Issue by MrVauxs** [robinraju/release-downloader#740]
**Describe the bug** No assets found in release.

**To Reproduce** 
I have the following action in a private repository:
```yml
name: Release Creation

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        
      - name: Download release asset file
        id: release_data
        uses: robinraju/release-downloader@v1.10
        with: 
          token: ${{ secrets.MY_TOKEN }} # Attempted with default (nothing), explicitly using GITHUB_TOKEN, and my own token.
          latest: true
          zipBall: true
```

**Expected behavior** 
The tarball zip being downloaded.

**Screenshots**
![chrome_ob34EDpVHw](https://github.com/robinraju/release-downloader/assets/32039708/f6396457-ebdb-4c62-a115-ddefe7d93cf9)

**Comment by robinraju** [comment]
Looks like #701 The fix for it is available on main but I haven't released a new version after that.

can you try

```
- uses: robinraju/release-downloader@cb096d8fa1fcb0e897f30b1c571f07e2c8e12479
  with:
    repository: "owner/repo"
    latest: true
    tarBall: true
    zipBall: true
```

I'll release a new version soon

**Comment by MrVauxs** [comment]
It works.

**Comment by robinraju** [comment]
@MrVauxs A new version is available now.

```
- uses: robinraju/release-downloader@v1.11
  with:
    repository: "owner/repo"
    latest: true
    tarBall: true
    zipBall: true
```
