### ISSUE TITLE
Download Tag without Release

### ISSUE THREAD

**Issue by TiloGit** [robinraju/release-downloader#773]
Trying to download the zip of a tag which doesn't have a release. 

Error:   `Error: [getReleaseByTag] Unexpected response: 404`

**To Reproduce** Steps to reproduce the behavior:

1. Have repo with tag which has no release
2. Try to download zip of that tag

**Expected behavior** A clear and concise description of what you expected to
happen.

- Download zip file  

**Action Environment (please complete the following information):**

- OS: [ ubuntu-latest]  
- Image: ubuntu-24.04  Version: 20250120.5.0 
```
- Run robinraju/release-downloader@v1
  with:
    repository: TSOSolutions/MyRepo123
    zipBall: true
    tag: tso_2025-01-27at1738015333
    token: ***
    latest: false
    preRelease: false
    tarBall: false
    out-file-path: .
    extract: false
    github-api-url: https://api.github.com/
```

**Additional context** Add any other context about the problem here.
- After I create a release for the tag the download works fine.
