### ISSUE TITLE
[getReleaseById] Unexpected response: 403

### ISSUE THREAD

**Issue by MaxRayskiy** [robinraju/release-downloader#796]
We started getting the error `[getReleaseById] Unexpected response: 403` in every ci/cd build, even though everything was working fine just yesterday

**To Reproduce**

use this action with `releaseId`

```
      - name: Download Ubuntu x86-64 Release
        if: ${{ matrix.os != 'fedora:39' }}
        uses: robinraju/release-downloader@daf26c55d821e836577a15f77d86ddc078948b05 # v1.12
        with:
          releaseId: ${{inputs.release_id}}
          fileName: "*${{matrix.name}}-dev.deb"
```
[src](https://github.com/MeshInspector/MeshLib/blob/370f7983bab631971e8b19e1711c756a4cc1e996/.github/workflows/test-distribution.yml#L47)

**Expected behavior** Find and download file by releaseId and fileName

**Screenshots** 
<img width="1043" alt="Image" src="https://github.com/user-attachments/assets/f0433dd0-8a83-472d-bb86-94b4d5bd07b9" />
[src](https://github.com/MeshInspector/MeshLib/actions/runs/14314460517/job/40122512277#step:4:1)

**Action Environment (please complete the following information):**

- OS: `ubuntu-latest` (in docker container), `macos-13`

**Additional context** 
`$ gh api /repos/MeshInspector/MeshLib/releases/210805025` works and returns release with all the assets

**Comment by slaivyn** [comment]
same problem here
```
      - name: Download release
        uses: robinraju/release-downloader@v1.10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          releaseId: ${{ needs.publish-happ.outputs.releaseId }}
          fileName: "my_file_name"
          out-file-path: "workdir/"
```
I tried quoting the releaseId (like that: `releaseId: "${{ needs.publish-happ.outputs.releaseId }}"`) as it is a string in the doc but it is not better
