### ISSUE TITLE
Verify Provenance Option

### ISSUE THREAD

**Issue by maennchen** [robinraju/release-downloader#802]
**Is your feature request related to a problem? Please describe.**

Lots of projects implement build provenance attestations for their release artifacts.

**Describe the solution you'd like**

I would like to introduce some options to verify the provenance attestations of the downloaded artifacts.

**Describe alternatives you've considered**

I've implemented this manually in an action of mine, but having support built-in would make it simpler for users to implement it safely.

https://github.com/erlef/mix-dependency-submission/blob/03107327592a517a54b497eaec2ac9da7eb35e86/action.yml#L26-L42

```yml
    - name: "Download Dependency Submission Tool"
      uses: robinraju/release-downloader@daf26c55d821e836577a15f77d86ddc078948b05 # v1.12
      with:
        repository: "erlef/mix-dependency-submission"
        tag: "v1.0.0-beta.8"
        fileName: "mix_dependency_submission_linux_amd64"
        out-file-path: "${{ runner.temp }}"
    - name: "Verify Dependency Submission Tool Provenance"
      run: |
        gh attestation \
          verify \
          --repo erlef/mix-dependency-submission \
          "${{ runner.temp }}/mix_dependency_submission_linux_amd64"
      shell: "bash"
      working-directory: "${{ runner.temp }}"
      env:
        GITHUB_TOKEN: ${{ github.token }}
```

**Additional context**

* https://docs.github.com/en/actions/security-for-github-actions/using-artifact-attestations/using-artifact-attestations-to-establish-provenance-for-builds
* https://github.com/actions/attest
