### ISSUE TITLE
Support for downloading multiple tags at once

### ISSUE THREAD

**Issue by MohammadRaziei** [robinraju/release-downloader#822]
Hi there 👋

First of all, thank you so much to @robinraju and everyone involved in building and maintaining [`robinraju/release-downloader`](https://github.com/robinraju/release-downloader)! This action has been super helpful in automating the download of release assets from GitHub.

However, I wanted to suggest a small improvement that could make this tool even more powerful.

Right now, if we want to download assets from **multiple tags**, we have to run the action **multiple times**, each with a different `tag`. That works, but it's repetitive and not very efficient.

It would be great if we could specify **multiple tags at once**, something like this:

```yaml
- name: Download Fonts
  uses: robinraju/release-downloader@v1.8
  with:
    tag: "Latex-lite", "fa-Yas", "fa-XBseries"
    repository: "mohammadraziei/fonts"
    fileName: "fonts.zip"
    out-file-path: "fonts"
    extract: true
```

This way, we can download assets from multiple tags in a single step — which would save time and keep workflows clean.

If this is already possible in another way or if there are any workarounds, I'd really appreciate your guidance! Otherwise, I’d be happy to help contribute or open a feature request.

Thanks again for your hard work 🙌  
Have a great day!
